### ISSUE TITLE
Remove redesign-for-ui branch

### ISSUE THREAD

**Issue by 20kdc** [CCDirectLink/CCUpdaterCLI#40]
I... actually don't know how this happened.

**Comment by 2767mr** [comment]
Will be removed once no longer needed

**Comment by 20kdc** [comment]
Wait, so it WASN'T GitHub doing this?

**Comment by 20kdc** [comment]
Then what exactly DID do it!??!?!!

**Comment by keanuplayz** [comment]
No.

**Comment by keanuplayz** [comment]
It wasn't GitHub.
